#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

register_user:
    path:     "%urls.register_user%"
    defaults: { _controller: "AppBundle:User:register" }
    methods:  [GET, POST]

thanks_for_registering:
    path:     "%urls.thanks_for_registering%"
    defaults: { _controller: "AppBundle:User:welcome" }
    methods:  GET

activation_error:
    path:     "%urls.activation_error%"
    defaults: { _controller: "AppBundle:User:activateError" }
    methods:  GET

activate_user:
    path:     "%urls.activate_user%"
    defaults: { _controller: "AppBundle:User:activate" }
    methods:  GET

user_login:
    path:     "%urls.user_login%"
    defaults: { _controller: "AppBundle:User:login" }
    methods:  [GET, POST]

login_error:
    path:     "%urls.login_error%"
    defaults: { _controller: "AppBundle:User:loginError" }
    methods:  GET

user_logout:
    path:     "%urls.user_logout%"
    defaults: { _controller: "AppBundle:User:logout" }
    methods:  GET

forgot_password:
    path:     "%urls.forgot_password%"
    defaults: { _controller: "AppBundle:User:forgotPassword" }
    methods:  [GET, POST]

sent_password_email:
    path:     "%urls.sent_password_email%"
    defaults: { _controller: "AppBundle:User:sentPasswordEmail" }
    methods:  GET

new_password:
    path:     "%urls.new_password%"
    defaults: { _controller: "AppBundle:User:newPassword" }
    methods:  [GET, POST]

user_index:
    path:     "%urls.user_index%"
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_edit:
    path:     "%urls.user_edit%"
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     "%urls.user_delete%"
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  DELETE
